DROP PROCEDURE IF EXISTS `addcol`;
CREATE PROCEDURE `addcol`()

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
    ALTER TABLE `un_quiz_r_student_quiz` ADD COLUMN `timestamp`  timestamp NULL ON UPDATE CURRENT_TIMESTAMP AFTER `params`;
END;

CALL `addcol`();
DROP PROCEDURE `addcol`;
