DELETE FROM #__comprofiler_field_values WHERE fieldid = 70;

INSERT INTO `#__comprofiler_field_values` (`fieldid`, `fieldtitle`, `fieldlabel`, `fieldgroup`, `ordering`, `sys`) VALUES
(70, 'Assistente sanitario', '', 0, 0, 0),
(70, 'Biologo/Anatomia patologica', '', 0, 0, 0),
(70, 'Biologo/Biochimica clinica', '', 0, 0, 0),
(70, 'Biologo/Igiene degli alimenti e della nutrizione', '', 0, 0, 0),
(70, 'Biologo/Igiene, epidemiologia e sanità pubblica', '', 0, 0, 0),
(70, 'Biologo/Laboratorio di genetica medica', '', 0, 0, 0),
(70, 'Biologo/Medicina del lavoro e sicurezza degli ambienti di lavoro', '', 0, 0, 0),
(70, 'Biologo/Medicina nucleare', '', 0, 0, 0),
(70, 'Biologo/Medicina trasfusionale', '', 0, 0, 0),
(70, 'Biologo/Microbiologia e virologia', '', 0, 0, 0),
(70, 'Biologo/Patologia clinica (laboratorio di analisi chimico – cliniche e microbiologia)', '', 0, 0, 0),
(70, 'Chimico/Biochimica clinica', '', 0, 0, 0),
(70, 'Chimico/Igiene degli alimenti e della nutrizione', '', 0, 0, 0),
(70, 'Chimico/Patologia clinica (laboratorio di analisi chimico – cliniche e microbiologia)', '', 0, 0, 0),
(70, 'Dietista', '', 0, 0, 0),
(70, 'Dietista/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Educatore professionale', '', 0, 0, 0),
(70, 'Educatore professionale/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Farmacista/Farmacia territoriale', '', 0, 0, 0),
(70, 'Farmacista/Farmacia pubblico del SSN', '', 0, 0, 0),
(70, 'Farmacista/Farmacia di altro settore', '', 0, 0, 0),
(70, 'Farmacista/Igiene, epidemiologia e sanità pubblica', '', 0, 0, 0),
(70, 'Fisico/Fisica', '', 0, 0, 0),
(70, 'Fisioterapista', '', 0, 0, 0),
(70, 'Fisioterapista/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Igienista dentale', '', 0, 0, 0),
(70, 'Igienista dentale/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Infermiere', '', 0, 0, 0),
(70, 'Infermiere pediatrico', '', 0, 0, 0),
(70, 'Logopedista', '', 0, 0, 0),
(70, 'Logopedista/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Massofisioterapista Iscritto all\'elenco speciale di cui allart. 5 del D.M. 9 agosto 2019', '', 0, 0, 0),
(70, 'Medico Chirurgo/Allergologia e immunologia clinica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Anatomia patologica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Anestesia e rianimazione', '', 0, 0, 0),
(70, 'Medico Chirurgo/Angiologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Audiologia e foniatria', '', 0, 0, 0),
(70, 'Medico Chirurgo/Biochimica clinica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Cardiochirurgia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Cardiologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Chirurgia generale', '', 0, 0, 0),
(70, 'Medico Chirurgo/Chirurgia maxillo-facciale', '', 0, 0, 0),
(70, 'Medico Chirurgo/Chirurgia pediatrica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Chirurgia plastica e ricostruttiva', '', 0, 0, 0),
(70, 'Medico Chirurgo/Chirurgia toracica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Chirurgia vascolare', '', 0, 0, 0),
(70, 'Medico Chirurgo/Continuità assistenziale', '', 0, 0, 0),
(70, 'Medico Chirurgo/Cure palliative', '', 0, 0, 0),
(70, 'Medico Chirurgo/Dermatologia e venereologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Direzione medica di presidio ospedaliero', '', 0, 0, 0),
(70, 'Medico Chirurgo/Ematologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Endocrinologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Epidemiologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Farmacologia e tossicologia clinica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Gastroenterologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Genetica medica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Geriatria', '', 0, 0, 0),
(70, 'Medico Chirurgo/Ginecologia e ostetricia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Igiene degli alimenti e della nutrizione', '', 0, 0, 0),
(70, 'Medico Chirurgo/Igiene, epidemiologia e sanità pubblica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Laboratorio di genetica medica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Malattie dell\'apparato respiratorio', '', 0, 0, 0),
(70, 'Medico Chirurgo/Malattie infettive', '', 0, 0, 0),
(70, 'Medico Chirurgo/Malattie metaboliche e diabetologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina aeronautica e spaziale', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina del lavoro e sicurezza degli ambienti di lavoro', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina della comunità', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina dello sport', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina e chirurgia di accettazione e di urgenza', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina fisica e riabilitazione', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina generale (medici di famiglia)', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina interna', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina legale', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina nucleare', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina subacquea e iperbarica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina termale', '', 0, 0, 0),
(70, 'Medico Chirurgo/Medicina trasfusionale', '', 0, 0, 0),
(70, 'Medico Chirurgo/Microbiologia e virologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Nefrologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Neonatologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Neurochirurgia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Neurofisiopatologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Neurologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Neuropsichiatria infantile', '', 0, 0, 0),
(70, 'Medico Chirurgo/Neuroradiologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Oftalmologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Oncologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Organizzazione dei servizi sanitari di base', '', 0, 0, 0),
(70, 'Medico Chirurgo/Ortopedia e traumatologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Otorinolaringoiatria', '', 0, 0, 0),
(70, 'Medico Chirurgo/Patologia clinica (laboratorio di analisi chimico-cliniche e microbiologia)', '', 0, 0, 0),
(70, 'Medico Chirurgo/Pediatria (pediatri di libera scelta)', '', 0, 0, 0),
(70, 'Medico Chirurgo/Psichiatria', '', 0, 0, 0),
(70, 'Medico Chirurgo/Psicoterapia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Radiodiagnostica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Radioterapia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Reumatologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Scienza dell\'alimentazione e dietetica', '', 0, 0, 0),
(70, 'Medico Chirurgo/Urologia', '', 0, 0, 0),
(70, 'Medico Chirurgo/Privo di specializzazione', '', 0, 0, 0),
(70, 'Odontoiatra', '', 0, 0, 0),
(70, 'Ortottista/Assistente di oftalmologia', '', 0, 0, 0),
(70, 'Ortottista/assistente di oftalmologia/ Iscritto nellelenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Ostetrica/o', '', 0, 0, 0),
(70, 'Podologo', '', 0, 0, 0),
(70, 'Podologo/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Psicologo/Psicologia', '', 0, 0, 0),
(70, 'Psicologo/Psicoterapia', '', 0, 0, 0),
(70, 'Psicologo/ Igiene, epidemiologia e sanità pubblica', '', 0, 0, 0),
(70, 'Tecnico audiometrista', '', 0, 0, 0),
(70, 'Tecnico audiometrista/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico audioprotesista', '', 0, 0, 0),
(70, 'Tecnico audioprotesista/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico della fisiopatologia cardiocircolatoria e perfusione cardiovascolare', '', 0, 0, 0),
(70, 'Tecnico della fisiopatologia cardiocircolatoria e perfusione cardiovascolare/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico della prevenzione nell\'ambiente e nei luoghi di lavoro', '', 0, 0, 0),
(70, 'Tecnico della prevenzione nell\'ambiente e nei luoghi di lavoro/ Iscritto nellelenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico della riabilitazione psichiatrica', '', 0, 0, 0),
(70, 'Tecnico della riabilitazione psichiatrica/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico di neurofisiopatologia', '', 0, 0, 0),
(70, 'Tecnico di neurofisiopatologia/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico ortopedico', '', 0, 0, 0),
(70, 'Tecnico ortopedico/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico sanitario laboratorio biomedico', '', 0, 0, 0),
(70, 'Tecnico sanitario laboratorio biomedico/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Tecnico sanitario di radiologia medica', '', 0, 0, 0),
(70, 'Terapista della neuro e psicomotricità dell\'età evolutiva', '', 0, 0, 0),
(70, 'Terapista della neuro e psicomotricità dell\'età evolutiva/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Terapista occupazionale', '', 0, 0, 0),
(70, 'Terapista occupazionale/ Iscritto nell\'elenco speciale ad esaurimento', '', 0, 0, 0),
(70, 'Veterinario/Igiene degli allevamenti e delle produzioni zootecniche', '', 0, 0, 0),
(70, 'Veterinario/Igiene, epidemiologia e sanità pubblica', '', 0, 0, 0),
(70, 'Veterinario/Igiene, produzione, trasformazione, commercializzazione conservazione e trasporto alimenti di origine animale e derivati', '', 0, 0, 0),
(70, 'Veterinario/Sanità animale', '', 0, 0, 0),
(70, 'Altro / NON ECM', '', 0, 0, 0);